#Build
FROM node:24.14.0-alpine AS builder

WORKDIR /app

RUN corepack enable

COPY . .

RUN npm install

RUN npm run build --filter=api...

#Prod API
FROM node:24.14.0-alpine AS prod

WORKDIR /app/apps/api

RUN corepack enable

COPY --from=builder /app/apps/api ./

RUN npm install --omit=dev

ENV NODE_ENV=production
ENV PORT=3001

EXPOSE 3001

CMD ["node", "dist/index.js"]